// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "github.com/yutkin/vegeta/v12/lib"
)

func main() {
  g := gen.NewGenerator("results_easyjson.go")
  g.SetPkg("vegeta", "github.com/yutkin/vegeta/v12/lib")
  g.NoStdMarshalers()
  g.Add(pkg.EasyJSON_exporter_jsonResult(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
